CREATE TABLE IF NOT EXISTS nevjegyek (
	id smallint(5) unsigned NOT NULL AUTO_INCREMENT,
	foto varchar(64) NOT NULL DEFAULT 'nincskep.png',
	nev varchar(20) DEFAULT NULL,
	cegnev varchar(77) DEFAULT NULL,
	foglakozas varchar(60) DEFAULT NULL,
	email varchar(28) DEFAULT NULL,
	mobil varchar(13) DEFAULT NULL,
	PRIMARY KEY (id)
);

INSERT INTO nevjegyek (id, foto, nev, cegnev, foglakozas, email, mobil) VALUES
(4, 'nincskep.png', 'Bognár Csanád', 'Rimai Coalitio', 'Bolti pénztáros', 'bognar.csanad@freemail.hu', '(70) 126-1342'),
(5, 'nincskep.png', 'Katona Taksony', 'K&H Bank', 'Területi közig., igazságszolg. közép vezetője', 'taksony_katona@vipmail.hu', '(70) 668-3833'),
(6, 'nincskep.png', 'Antal Ilona', 'Genesis Energy Nyrt.', 'Kereskedelmi részegység vezetője', 'antal.ilona@hotmail.com', '(20) 346-3148'),
(7, 'nincskep.png', 'Barta Kristóf', 'NIK Központi Autótervező Iroda', 'Cipész, cipőkészítő, -javító', 'k.barta@gmail.com', '(30) 618-9109'),
(8, 'nincskep.png', 'Orbán Anasztáz', 'HEINEKEN Hungária Sörgyárak Zrt.', 'Középfokú oktatási intézmény szakoktatója', 'anasztaz.orban@yahoo.com', '(20) 470-1547'),
(9, 'nincskep.png', 'Kis Alex', 'Pécsi Dohánygyár', 'Vájár, segédvájár', 'kis_alex@gmail.com', '(30) 356-1144'),
(10, 'nincskep.png', 'Nagy Aletta', 'Toti Sport', 'Bolti pénztáros', 'a.nagy@yahoo.com', '(70) 194-8179'),
(11, 'nincskep.png', 'Nemes Eulália', 'Digic Pictures', 'Fegyveres erők felsőfokú foglalkozásai', 'eulalia_nemes@gmail.com', '(20) 907-7812'),
(12, 'nincskep.png', 'Bakos Emil', 'Moskovits Sámuel vasöntödéje és gépgyára', 'Szállító- és rakodómunkás', 'bakos.emil@freemail.hu', '(30) 614-7177'),
(13, 'nincskep.png', 'Kis Diána', 'Concorde Csoport', 'Egyéb műszaki foglalkozások', 'diana_kis@mailbox.hu', '(20) 425-8210'),
(14, 'nincskep.png', 'Nagy Kelemen', 'Concorde Csoport', 'Egyéb szakképzett oktatók, nevelők', 'k.nagy@freemail.hu', '(20) 549-3060'),
(15, 'nincskep.png', 'Horváth Margit', 'InfoRádió', 'Bútorasztalos', 'margit.horvath@hotmail.com', '(70) 531-6569'),
(16, 'nincskep.png', 'Kiss Dénes', 'Goodwill Communications', 'Fegyveres erők felsőfokú foglalkozásai', 'denes_kiss@hotmail.com', '(30) 587-8352'),
(17, 'nincskep.png', 'Szűcs Andrea', 'Offset és Játékkártya Nyomda Zrt.', 'Egyéb műszaki foglalkozások', 'andrea.szucs@freemail.hu', '(70) 218-2486'),
(18, 'nincskep.png', 'Kocsis Krisztina', 'Dunai Vasmű', 'Szociális munkás', 'kocsis.krisztina@gmail.com', '(30) 582-3853'),
(19, 'nincskep.png', 'Vincze János', 'Első Magyar Cérnagyár', 'Minőségi, műszaki, biztonsági ellenőr', 'vincze_janos@freemail.hu', '(20) 107-4404'),
(20, 'nincskep.png', 'Hegedűs György', 'Cartographia', 'Általános orvos', 'gyorgy_hegedus@freemail.hu', '(30) 653-4082'),
(21, 'nincskep.png', 'Molnár Jenő', 'Első Nemzeti Közműszolgáltató', 'Szövő', 'jeno.molnar@citromail.hu', '(20) 459-4843'),
(22, 'nincskep.png', 'Sándor Apor', 'Nézőpont Intézet', 'Mosónő, vasalónő', 'sandor.apor@freemail.hu', '(70) 995-1103'),
(23, 'nincskep.png', 'Halász Rozália', 'Merck', 'Hegesztő, lángvágó', 'rozalia.halasz@gmail.com', '(20) 766-7351'),
(24, 'nincskep.png', 'Balla Ibolya', 'Centrum Áruházak', 'Kazángépkezelő (vizsgázott kazánfűtő)', 'balla.ibolya@gmail.com', '(20) 925-4219'),
(25, 'nincskep.png', 'Szabó Virgínia', 'Raiffeisen Bank (Magyarország)', 'Felsőfokú tanintézeti tanár, oktató', 'v.szabo@yahoo.com', '(20) 915-5028'),
(26, 'nincskep.png', 'Fekete Ferenc', 'Vidanet', 'Óvónő', 'fekete.ferenc@gmail.com', '(30) 976-6445'),
(27, 'nincskep.png', 'Hegedűs Benedek', 'Index (internetes újság)', 'Számviteli és pénzügyi részegység vezetője', 'benedek_hegedus@freemail.hu', '(30) 682-1804'),
(28, 'nincskep.png', 'Fodor Magdolna', 'Zoltán Hugó és Társa', 'Egyéb pedagógusok', 'magdolna_fodor@vipmail.hu', '(20) 751-8304'),
(29, 'nincskep.png', 'Szűcs Gusztáv', 'T-Mobile (Magyar Telekom Csoport)', 'Mechanikai műszerész', 'szucs_gusztav@vipmail.hu', '(20) 213-1955'),
(30, 'nincskep.png', 'Németh Taksony', 'Kner nyomda', 'Pénzügyi ügyintéző', 't.nemeth@hotmail.com', '(20) 626-9632'),
(31, 'nincskep.png', 'Magyar Teodóra', 'Hajós- és Szántó Elektromos Gyára Rt.', 'Vegyészmérnök', 't.magyar@upc.hu', '(30) 634-9864'),
(32, 'nincskep.png', 'Király Édua', 'HospInvest Zrt.', 'Oktatási részegység vezetője', 'edua.kiraly@hotmail.com', '(30) 569-2536'),
(33, '1443198181.jpg', 'Antal F', 'Virtual Call Center Solutions Zrt.', 'Középiskolai tanár, oktató', 'felix.antal@vipmail.hu', '(70) 843-4487'),
(34, 'nincskep.png', 'Pintér Kartal', 'Pick Szeged Zrt.', 'Kereskedelmi részegység vezetője', 'pinter.kartal@yahoo.com', '(30) 411-8240'),
(35, 'nincskep.png', 'Budai Frigyes', 'Magyar Turizmus Zrt.', 'Nehézföldmunkagép-kezelő', 'budai_frigyes@vipmail.hu', '(70) 438-5219'),
(36, 'nincskep.png', 'Vincze Vazul', 'HospInvest Zrt.', 'Fegyveres erők felsőfokú foglalkozásai', 'vincze.vazul@gmail.com', '(20) 159-6994'),
(37, 'nincskep.png', 'Farkas Damján', 'Raiffeisen Bank (Magyarország)', 'Egyéb termelői, szolg. részegységek vezetői', 'd.farkas@indamail.hu', '(30) 670-2868'),
(38, 'nincskep.png', 'Sándor Xénia', 'Kinizsi Bank', 'Egészségügyi és szoc. szolg. részegység vezetője', 'xenia.sandor@freemail.hu', '(70) 718-7929'),
(39, 'nincskep.png', 'Varga Viola', 'Elektronikus Mérőkészülékek Gyára (Sashalom)', 'Ügyvéd', 'v.varga@gmail.com', '(30) 132-3593'),
(40, 'nincskep.png', 'Dudás Edgár', 'Minimal Art Family', 'Újságíró', 'edgar_dudas@gmail.com', '(20) 391-8580'),
(41, 'nincskep.png', 'Horváth Hilária', 'Hungarotex', 'Fodrász, borbély', 'h.horvath@freemail.hu', '(30) 712-4304'),
(42, 'nincskep.png', 'Kiss Lőrinc', 'Toti Sport', 'Általános orvos', 'kiss_lorinc@freemail.hu', '(30) 939-2149'),
(43, 'nincskep.png', 'Barna Valter', 'Bárdi Autó Zrt.', 'Felszolgáló, vendéglátóipari eladó', 'barna_valter@vipmail.hu', '(30) 476-6957'),
(44, 'nincskep.png', 'Balázs Ágoston', 'IFUA Horváth & Partners', 'Kereskedelmi kisszervezet vezetője', 'agoston.balazs@hotmail.com', '(30) 308-7837'),
(45, 'nincskep.png', 'Szőke Egon', 'Dorogi hanglemezgyár', 'Fordító, tolmács', 'egon.szoke@gmail.com', '(70) 881-3975'),
(46, 'nincskep.png', 'Kis Aida', 'CTnetwork', 'Számviteli és pénzügyi részegység vezetője', 'kis.aida@gmail.com', '(30) 758-4737'),
(47, 'nincskep.png', 'Balog Flóra', 'FM1 Konzorcium', 'Ipari kisszervezet vezetője', 'balog.flora@freemail.hu', '(70) 179-3710'),
(48, 'nincskep.png', 'Jakab Mária', 'Aegon Magyarország Pénztárszolgáltató Rt.', 'Fodrász, borbély', 'jakab.maria@yahoo.com', '(30) 423-1600'),
(49, 'nincskep.png', 'Papp Tihamér', 'Murányi Unió', 'Bérelszámoló', 'papp_tihamer@freemail.hu', '(70) 518-7226'),
(50, 'nincskep.png', 'Balázs Szeréna', 'Diósgyőri Gépgyár', 'Felsőfokú tanintézeti tanár, oktató', 'balazs.szerena@mailbox.hu', '(20) 885-1579'),
(51, 'nincskep.png', 'Fábián Annamária', 'Nemzeti Infrastruktúra-fejlesztő Zrt.', 'Épületasztalos', 'a.fabian@indamail.hu', '(20) 649-1835'),
(52, 'nincskep.png', 'Jakab Ulrika', 'Tarr Kft.', 'Szakasszisztens (orvosi)', 'jakab_ulrika@gmail.com', '(20) 939-3100'),
(53, 'nincskep.png', 'Sándor Veronika', 'Dunai Vasmű', 'Erősáramú villamosmérnök', 'veronika_sandor@gmail.com', '(30) 377-6067'),
(54, 'nincskep.png', 'Bogdán Bánk', 'MAL Magyar Alumínium Termelő és Kereskedelmi Zrt.', 'Kézi anyagmozgató, csomagoló', 'b.bogdan@gmail.com', '(30) 830-1382'),
(55, 'nincskep.png', 'Pásztor Elizeus', 'ÁPISZ', 'Mechanikai műszerész', 'e.pasztor@yahoo.com', '(30) 756-7914'),
(56, 'nincskep.png', 'Szabó Gergely', 'Dorogi hőerőmű', 'Általános iskolai tanár, tanító, oktató', 'g.szabo@freemail.hu', '(70) 783-5243'),
(57, 'nincskep.png', 'Veres Aranka', 'Fehér Ferenc Precíziós Mechanikai és Gépműhelye', 'Egyéb szakképzett oktatók, nevelők', 'veres.aranka@freemail.hu', '(30) 707-4449'),
(58, 'nincskep.png', 'Simon Brúnó', 'Auguszt Cukrászda', 'Kereskedelmi részegység vezetője', 'bruno_simon@gmail.com', '(70) 756-1051'),
(59, 'nincskep.png', 'Boros Zakariás', 'Melléktermék- és Hulladékhasznosító Vállalat', 'Kézi anyagmozgató, csomagoló', 'zakarias_boros@mailbox.hu', '(70) 636-4264'),
(60, 'nincskep.png', 'Farkas Tétény', 'IFUA Horváth & Partners', 'Háztömbfelügyelő, házfelügyelő, házgondnok', 'farkas.teteny@gmail.com', '(20) 440-1633'),
(61, 'nincskep.png', 'Virág Dzsenifer', 'Vodafone', 'Szakasszisztens (orvosi)', 'dzsenifer.virag@freemail.hu', '(20) 937-9599'),
(62, 'nincskep.png', 'Somogyi Cecília', 'ANY Biztonsági Nyomda', 'Oktatási szolgáltatási kisszervezet vezetője', 'c.somogyi@gmail.com', '(70) 187-3210'),
(63, 'nincskep.png', 'Magyar Márta,Flóra', 'ProfiPower', 'Területi közig., igazságszolg. közép vezetője', 'm.magyar@hotmail.com', '(70) 906-8973'),
(64, 'nincskep.png', 'Oláh Paula', 'Sanoma Budapest Zrt.', 'Egyéb növénytermesztési és kertészeti foglalkozások', 'olah.paula@yahoo.com', '(70) 647-6588'),
(65, 'nincskep.png', 'Pataki Matilda', 'Globex Holding', 'Mosónő, vasalónő', 'pataki.matilda@gmail.com', '(20) 369-3664'),
(66, 'nincskep.png', 'Boros Szaniszló', 'Petőfi Nyomda', 'Szakács', 'szaniszlo.boros@indamail.hu', '(70) 725-7827'),
(67, 'nincskep.png', 'Orosz Egyed', 'Salgótarjáni Öblösüveggyár', 'Oktatási szolgáltatási kisszervezet vezetője', 'orosz_egyed@gmail.com', '(20) 988-2478'),
(68, 'nincskep.png', 'Dudás Valentin', 'FŐTÁV Zrt.', 'Bér- és társadalombiztosítási ügyintéző', 'valentin.dudas@gmail.com', '(70) 485-4700'),
(69, 'nincskep.png', 'Király Jusztina', 'Offset és Játékkártya Nyomda Zrt.', 'Gyógypedagógus', 'kiraly_jusztina@citromail.hu', '(30) 603-8769'),
(70, 'nincskep.png', 'Balog Frigyes', 'MVM Magyar Villamos Művek Zrt.', 'Szakápoló', 'balog.frigyes@gmail.com', '(70) 586-9614'),
(71, 'nincskep.png', 'Borbély Kunigunda', 'Telefongyár', 'Szállítási és raktározási részegység közv. term.ir.', 'k.borbely@yahoo.com', '(70) 270-9717'),
(72, 'nincskep.png', 'Dudás Oszkár', 'Röck István Gépgyára', 'Iparművész', 'dudas.oszkar@vipmail.hu', '(20) 637-5737'),
(73, 'nincskep.png', 'Deák Paulina', 'Auguszt Cukrászda', 'Egyéb irodai jellegű foglalkozások', 'p.deak@indamail.hu', '(70) 124-7532'),
(74, 'nincskep.png', 'Fazekas Richárd', 'Miskolci Gőztéglagyár', 'Ipari részegység vezetője', 'r.fazekas@gmail.com', '(70) 494-6946'),
(75, 'nincskep.png', 'Hajdú Valér', 'Magyar Pénzügyi Közvetítő Zrt.', 'Fegyveres erők felsőfokú foglalkozásai', 'valer.hajdu@freemail.hu', '(30) 650-3078'),
(76, 'nincskep.png', 'Kozma Kartal', 'Moskovits Sámuel vasöntödéje és gépgyára', 'Építőipari részegység vezetője', 'kartal.kozma@yahoo.com', '(70) 559-2828'),
(77, 'nincskep.png', 'Borbély Mária', 'Versys Clinics', 'Vezeték- és csőhálózat-szerelő', 'maria.borbely@mailbox.hu', '(30) 569-8800'),
(78, 'nincskep.png', 'Budai Franciska', 'Herendi Porcelánmanufaktúra', 'Védőnő', 'budai_franciska@yahoo.com', '(30) 134-6204'),
(79, 'nincskep.png', 'Halász Emánuel', 'Labor Műszeripari Művek', 'Egyéb magasan képzett ügyintézők', 'halasz_emanuel@mailbox.hu', '(70) 512-1472'),
(80, 'nincskep.png', 'Virág Szilárd', 'K&H Bank', 'Egyéb magasan képzett ügyintézők', 'virag_szilard@gmail.com', '(70) 895-8552'),
(81, 'nincskep.png', 'Hajdú Árpád', 'Zsolnay Porcelánmanufaktúra Zrt.', 'Szarvasmarhatartó és -tenyésztő', 'hajdu.arpad@gmail.com', '(20) 885-1150'),
(82, 'nincskep.png', 'Bogdán Imre', 'Borsodi Sörgyár Zrt.', 'Fegyveres erők felsőfokú foglalkozásai', 'imre.bogdan@gmail.com', '(30) 887-6175'),
(83, 'nincskep.png', 'Faragó Imelda', 'Pick Szeged Zrt.', 'Egyéb szakképzett oktatók, nevelők', 'i.farago@indamail.hu', '(70) 816-5736'),
(84, 'nincskep.png', 'Tamás Filippa', 'Dorogi hőerőmű', 'Óvónő', 'tamas_filippa@hotmail.com', '(70) 846-6079'),
(85, 'nincskep.png', 'Budai Gellért', 'Petőfi Nyomda', 'Ipari kisszervezet vezetője', 'g.budai@citromail.hu', '(30) 832-3064'),
(86, 'nincskep.png', 'Szilágyi Atanáz', 'MAL Magyar Alumínium Termelő és Kereskedelmi Zrt.', 'Szakorvos', 'szilagyi_atanaz@vipmail.hu', '(30) 333-6057'),
(87, 'nincskep.png', 'Bogdán Botond', 'Invitel', 'Gyengeáramú villamosmérnök', 'bogdan.botond@gmail.com', '(30) 891-4250'),
(88, 'nincskep.png', 'Szűcs Margit', 'MATERal', 'Fegyveres erők középfokú foglalkozásai', 'margit.szucs@yahoo.com', '(70) 187-6512'),
(89, 'nincskep.png', 'Szőke Placida', 'Gyulaj Erdészeti és Vadászati Zrt.', 'Cipész, cipőkészítő, -javító', 'szoke.placida@freemail.hu', '(70) 661-2364'),
(90, 'nincskep.png', 'Gál János', 'ELTE Idegennyelvi Továbbképző Központ', 'Szállító- és rakodómunkás', 'j.gal@freemail.hu', '(30) 198-4578'),
(91, 'nincskep.png', 'Lengyel Izidor', 'Gamma (gyár)', 'Hegesztő, lángvágó', 'izidor_lengyel@gmail.com', '(30) 149-9353'),
(92, 'nincskep.png', 'Németh Géza', 'Pécsi Bőrgyár', 'Postai kézbesítő', 'g.nemeth@gmail.com', '(30) 168-6167'),
(93, 'nincskep.png', 'Hegedűs Péter', 'Buda-Cash Brókerház Zrt.', 'Piackutató, marketingtevékenységet végző', 'p.hegedus@hotmail.com', '(70) 673-9769'),
(94, 'nincskep.png', 'Váradi Leó', 'Senior', 'Egészségügyi, oktatási szolgáltatási foglalkozások', 'l.varadi@gmail.com', '(30) 376-3507'),
(95, 'nincskep.png', 'Vincze Vince', 'Budapesti Finomkötöttárugyár', 'Egyéb szakképzett oktatók, nevelők', 'vince_vincze@indamail.hu', '(30) 114-3636'),
(96, 'nincskep.png', 'Fekete Eulália', 'REMIX Rádiótechnikai Vállalat', 'Ipari kisszervezet vezetője', 'eulalia.fekete@gmail.com', '(20) 212-7642'),
(97, 'nincskep.png', 'Pásztor Apor', 'Melléktermék- és Hulladékhasznosító Vállalat', 'Egyéb fémmegmunkálók, felületkezelők', 'a.pasztor@gmail.com', '(30) 649-4540'),
(98, 'nincskep.png', 'Oláh Emília', 'KDB Bank (Magyarország)', 'Mezőgazdasági vontatóvezető', 'olah.emilia@gmail.com', '(30) 660-4635'),
(99, 'nincskep.png', 'Balla Léda', 'Első Magyar Koncessziós Autópálya Rt.', 'Egyszerű szolgáltatási jellegű foglalkozások', 'l.balla@vipmail.hu', '(30) 878-3177'),
(100, 'nincskep.png', 'Hajdú Péter', 'Röck István Gépgyára', 'Egyéb növénytermesztési és kertészeti foglalkozások', 'p.hajdu@hotmail.com', '(30) 332-2332'),
(103, '1443198165.jpg', 'Aaaaaaaaaaaa', 'BBBBBBBBB', NULL, 'a@b.hu', '3333333333333');